### ISSUE TITLE
Question about safely wrapping this API

### ISSUE THREAD

**Issue by samdmarshall** [jackhftang/threadproxy.nim#2]
Hi! i'm trying to write a basic high level API around mixing Nim's thread and channel code to make something similar to [libdispatch](https://en.wikipedia.org/wiki/Grand_Central_Dispatch) where i can create queues that are backed by threads to  perform blocks of work on, and then get a result passed back. in doing this i have hit a snag that seems to be caused by the scope of where and how i'm using `threadproxy` in my implementation. First, some context:

(Note: this is all tested using version 1.4.2 of the language, other people have used other (newer) versions in helping me investigate but i don't know what those version numbers are atm)

* [Example 1](https://gist.github.com/samdmarshall/79cf2c5d629349e625b2b34756b3e92f): this basically mirrors your example of manually creating a worker thread, this compiles and runs successfully as intended.

* [Example 2](https://gist.github.com/samdmarshall/8c2879196e45a57384f7a54bffa70c28): this is the same thing, except i've begun to wrap the work of `threadproxy` behind my own API. the code is identical, only difference is the level of scope that everything is done in. this does compile, but will not run successfully due to attempting to deepcopy during the `createQueue` function call, where it tries to copy the thread and fails.

* [Example 3](https://gist.github.com/samdmarshall/f41ce155423776a2dfb44204d50958f4): this is the same as the previous example, except a new line has been added at [line 54](https://gist.github.com/samdmarshall/f41ce155423776a2dfb44204d50958f4#file-example2v2-nim-L54). i don't have to register a data handler (`onData ...:`) for this action, but as long as the thread gets "asked" there, then the rest of the code will work fine at runtime. i have a suspicion that this has to do with some internal reference to `threadproxy` that because i'm not interacting with the thread i just created manually in the same scope it doesn't get properly retained or marked as owned and will result in a crash from accessing nil.

My questions are:

1. What is going on in example 3 that isn't happening in example 2? Based on my understanding of Nim and the compiler, this level of abstraction/wrapping shouldn't cause significant behavioral changes in the memory safety or thread behavior, are there aspects of your code that could impact this that aren't explicitly documented?
2. Based on the nature of `waitFor` and how the code for the function/callback used to process work sent to the worker thread, i had assumed that a thread created by `threadproxy` was implicitly serial (only allowed one active operation per thread, any other operations added would block until it was their turn to be processed), and these operations were processed in fifo (first in, first out) order. it seems like the work is done in fifo order, but from what i can see, when asynchronously "asking" the thread to do work, will allow more than one active operation to be done at a time. should i be looking at the `push_m_jobs_to_n_workers` example code for how to properly implement that kind of serial queue? or would i still encounter the problem of having a single worker being able to actively process more than one concurrent operation?
3. i've looked at many of the libraries written in nim that deal with multithreading and parallelism using both the `asyncdispatch` and `thread`/`channel` apis, including your own `taskqueue` and `threadproxy` libraries. individually, these two libraries each get me halfway to my desired goal. i know enough about the problems to understand why implementing this in nim is difficult, and know that trying to build everything from scratch isn't any more feasible than building off existing solutions. however, given that you have implemented most of the two halves i need, do you see any way i could use what you have built to achieve my goal, or will i be faced with underlying structural problems with these implementations (am i better off building off something else instead)?

**Comment by jackhftang** [comment]
The most critical thing you need to know is that `Thread[T]` cannot be GC-ed, or at least it have to live longer than the thread. 

The reason why example2 fail is that you declared `var woker: Thread[QueueTask]` as a local variable. After the function exit `var worker` will be gc-ed. Then all operations on the thread will lead to error. As for why example2v2 work, I guess it is simply by luck. The added line changes the order of gc. 

If the line `var woker: Thread[QueueTask]` in example2 move to global variable like the following, it will works because Thread[QueueTask] now has a global reference. However, this is probably not what you want to achieve. In threadproxy, I created a data structure `ThreadWrapper` that is `ptr Thread[ThreadProxy]` to manually manage the lifetime of `Thread[T]` in `MainThreadProxy`(see alloc0, dealloc) to avoid GC involved.

```nim
# =======
# Imports
# =======


import json
import strformat
import asyncdispatch

import threadproxy

# =====
# Types
# =====

type
  Queue = object
    name: string
    token: ThreadToken
    thread: Thread[QueueTask]

  QueueTask = object
    token: ThreadToken

  QueueManager = object
    main: MainThreadProxy

  QueueMain = proc (task: QueueTask) {.thread, nimcall.}

# =========
# Functions
# =========

proc initQueueManager(name: string = "main"): QueueManager =
  let proxy = newMainThreadProxy(name)
  asyncCheck proxy.poll()

  proxy.onData "new":
    echo "action: new"
    return newJNull()

  proxy.onData "stop":
    proxy.stop()

  result = QueueManager(main: proxy)

var worker: Thread[QueueTask]
proc createQueue(ctx: QueueManager, name: string, main: QueueMain): Queue =
  let proxy = ctx.main
  echo "creating queue!"
  let token = proxy.createToken(name)
  createThread(worker, main, QueueTask(token: token))
  result = Queue(name: name, token: token, thread: worker)

proc dispatchAsync(ctx: QueueManager, queue: Queue, action: string, data: JsonNode): Future[JsonNode] =
  let proxy = ctx.main
  echo fmt"pushing ({action}) with '{data}' to thread: {queue.name}"
  result = proxy.ask(queue.name, action, data)


# =======
# Threads
# =======

proc workerMain(task: QueueTask) {.thread.} =
  let proxy = newThreadProxy(task.token)

  # register action handler
  proxy.onData "multiply":
    let x = data["value"].getInt()
    echo fmt"start processing task: {x}"
    return %*{"value": x + 20}

  # start processing channel
  waitFor proxy.poll()

proc response(f: Future[JsonNode]) =
  echo "future callback!"
  let data = f.read()
  let value = data["value"].getInt()
  echo fmt"{value - 20} -> {value}"
  echo fmt"finish processing task: {value - 20}"

# ===========
# Entry Point
# ===========

proc main() =
  var ctx = initQueueManager()

  var queue = ctx.createQueue("thread_1", workerMain)

  let index = 8
  # for index in 0..10:
  let data = %*{"value": index}
  echo "dispatching task: " & $data
  let answer = ctx.dispatchAsync(queue, "multiply", data)
  answer.addCallback response


  echo "done dispatching"
  runForever()

when isMainModule:
  main()
```

For question 2 & 3, threadproxy implements two channels per thread. They are called `channal` and `fastChannel`. `channal` is a FIFO (so does `fastChannel`) that append an event to the correct channel whenever `ask`, `send` is called. `fastChannel` is mainly for house keeping operations e.g. resolving thread name to thread's channel. The main reason of existence of `fastChannel` is to preempt `channel` (Actually, I want an preemptable channel, but Nim channel is a simple fifo). 

Although channel is a FIFO, the events are processed asynchronously. This means if the first event has some async operations and then during the awaiting of finishing of those async operations, the second event will be processed. When thread A call `ask` to thread B, there is an event append to the channel of thread B. After thread B process the event and return a `JsonNode`, the result will be sent as another event and append back to the channel of thread A. 

Another thing that you may need to know that `threadproxy` process channel by polling. It drains `fastChannel` and `channel` and then sleep and then drain again. This is not a very responsive way to process events, but Nim channel does not provide hooks API that threadproxy can listen to. If you want a fast responsive multi-threaded processing, one simple way is to not sleep and use cpuRelax() if your hardware support it or just let CPU 100% running or update Nim's channel to provide hooks API or use/build something else.

**Comment by jackhftang** [comment]
btw, just find [this](https://github.com/xflywind/channel). This provides `recv()` instead of polling. This is really cool.

**Comment by samdmarshall** [comment]
Thanks for the quick response! To give you some background context:

> i'm currently building ontop the [Jester](https://github.com/dom96/jester) web framework, when my application receives requests, it is going to need to check against:
> 1. the cache of html pages generated from rst source files
> 2. the rst source files to generate a page that it doesn't have in cache already
> 3. a number of static files that get served as-is (images, css, other assets, etc)
>
> due to the nature of jester, it handles each request asynchronously, i can easily have a situation where multiple requests need to access/operate on the same file. i need to create a way to manage this safely, now, I could do this by using locks; however that would get pretty ugly to manage (imo) - so i'd prefer to control the flow by having a dedicated place to do the sensitive work (my FIFO queue backed by a thread). the implementation here needs to be fairly high level and hands-off as i'm already in an async environment that i don't have control over (as it's internal to jester's coding). i know this really hits at a point that Nim is currently weak at solving (operations that are inherently unsafe to be made async, that need to communicate between threads), but was hoping your abstraction handled most of the heavy lifting here.

---

Now, regarding your responses:

> The reason why example2 fail is that you declared var woker: Thread[QueueTask] as a local variable. After the function exit var worker will be gc-ed. Then all operations on the thread will lead to error. As for why example2v2 work, I guess it is simply by luck. The added line changes the order of gc.
> 
> If the line var woker: Thread[QueueTask] in example2 move to global variable like the following, it will works because Thread[QueueTask] now has a global reference. However, this is probably not what you want to achieve. In threadproxy, I created a data structure ThreadWrapper that is ptr Thread[ThreadProxy] to manually manage the lifetime of Thread[T] in MainThreadProxy(see alloc0, dealloc) to avoid GC involved.

So for the code in example 2, is there any other way to work around this? The whole point of wrapping this code (also the manual thread creation) is that the intended use case wouldn't be able to accommodate the creation of a global variable each time a new "queue" gets created for use.

> For question 2 & 3, threadproxy implements two channels per thread. They are called channal and fastChannel. channal is a FIFO (so does fastChannel) that append an event to the correct channel whenever ask, send is called. fastChannel is mainly for house keeping operations e.g. resolving thread name to thread's channel. The main reason of existence of fastChannel is to preempt channel (Actually, I want an preemptable channel, but Nim channel is a simple fifo).
> 
> Although channel is a FIFO, the events are processed asynchronously. This means if the first event has some async operations and then during the awaiting of finishing of those async operations, the second event will be processed. When thread A call ask to thread B, there is an event append to the channel of thread B. After thread B process the event and return a JsonNode, the result will be sent as another event and append back to the channel of thread A.

Right, i understand that much; but is there no way to manage the processing of events to make it also FIFO? or is it inherent to the underlying implementation of channels in nim at the moment (something outside of your code's control)? (i am hoping for an answer regarding how actionable implementing this would be, as i need it regardless of if i build on your code or not.)

> Another thing that you may need to know that threadproxy process channel by polling. It drains fastChannel and channel and then sleep and then drain again. This is not a very responsive way to process events, but Nim channel does not provide hooks API that threadproxy can listen to. If you want a fast responsive multi-threaded processing, one simple way is to not sleep and use cpuRelax() if your hardware support it or just let CPU 100% running or update Nim's channel to provide hooks API or use/build something else.

So, based on the use-case i gave above, would you suggest i find something else to do the work here instead of `threadproxy`? my website doesn't get a huge amount of traffic, but it's enough that i'd have to care about the problems i've detailed so far. I haven't even gotten to the point of evaluating the performance of the executable yet as i'm trying to reason how to build it first.

**Comment by jackhftang** [comment]
So you want to have a dedicated thread for processing those file operations? It sounds to me you don't really want multi-threading, you just need a `Deque[Future[T]]`. Since your operation involve files, you will likely hit IO bound before CPU bound. If you ask me, I will just go with single-thread (it is easier to write, debug and reason and less code-noise and things to consider as in multi-thread env). I will create a `ResourcePool` and the resource is your file manager and you only have one. Not sure how ugly you think. 

Example
```nim
# example.nim
import htmlgen
import jester
import deques
import options

type
  ## Use this when the number of resource is pre-defined
  ## and have to dequeue before use and enqueue afterward
  ResourcePool*[T] = object
    resources: Deque[T]
    queuers: Deque[Future[T]]

proc rlen*[T](pool: ResourcePool[T]): int =
  pool.resources.len

proc qlen*[T](pool: ResourcePool[T]): int =
  pool.queuers.len

proc dequeue*[T](pool: var ResourcePool[T]): Future[T] = 
  ## Take one resource from pool. Wait if not available
  result = newFuture[T]("ResourcePool.dequeue")
  if pool.resources.len == 0:
    pool.queuers.addLast result
  else:
    result.complete pool.resources.popFirst()

proc tryDequeue*[T](pool: var ResourcePool[T]): Option[T] =
  ## Take one resource from pool. Do not wait if not available.
  if pool.resources.len == 0:
    result = none[T]()
  else:
    result = some pool.resources.popFirst()

proc enqueue*[T](pool: var ResourcePool[T], item: T) =
  ## Add one resource to pool.
  if pool.queuers.len > 0:
    pool.queuers.popFirst().complete(item)
  else:
    pool.resources.addLast(item)  

# create your own file manager here
type
  FileManager = ref object
    counter: int

proc doSomething(m: FileManager): Future[string] {.async.} =
  # customize the logic of FileManager here 
  echo "start doing something ", m.counter
  await sleepAsync 1000
  echo "finish ", m.counter
  m.counter += 1
  return "Hello world"

# create one FileManager and put it in pool
var pool: ResourcePool[FileManager]
pool.enqueue new(FileManager)

routes:
  get "/":
    # add these two lines whenever want a FileManager
    let fileManager = await pool.dequeue()
    defer: pool.enqueue(fileManager) 

    let res = await fileManager.doSomething()
    resp h1(res)

# run the following command 
# for i in {1..10}; do curl http://127.0.0.1:5000 &  done
# and see the sequence of operations in stdout
```

You probably want to put `pool` inside `FileManager` and abstract it away. Also, it seems a bit over-killed to use `ResourcePool` for single resource (here is just for a quick example), but this should give you some ideas on how handle async and write a higher level interface.

**Comment by samdmarshall** [comment]
Yes, what i want is exactly `Deque[proc (x: T): Future[T]]`, but backed by a thread, either a named/dedicated one or an anonymous one (one that gets spun up as needed). I see what you are trying to get at in the example code but don't see how it solves my problem, as `Deque` isn't access-safe - all i'd be doing is shifting the unsafe access from file operations to the management data structure (which brings me back to locks - as i mentioned, wanting to avoid, earlier). 

i know what i need to implement here, and how - i am just asking if this falls under "intended use" for this library you wrote - since i know the reason why my use case hasn't been implemented in Nim before, and before jumping too far ahead with the closest thing, want to make sure your intentions align with mine before wasting too much of my time writing code that might ultimately not work. i would appreciate it if you could address my remaining questions:
1. are global scope variables absolutely necessary for the manual creation of threads? (to avoid problems with memory management of the threads by the GC system)
2. is there a way to make event processing to "block" instead of being handled asynchronously? so even if events are still processed asynchronously, they will get added to the deque if there is one being processed actively, then steps have to be taken to start processing a new event off the stack (because i thought that was what your `push_m_jobs_to_n_workers` example was doing with the custom `process` method on the "worker" thread, and in my case i'd be pushing M jobs to N workers where M=? and N=1).
3. what was your reasoning for using `JsonNode` as the type for communication between threads rather than a generic `T` that could be supplied by the library consumer? (i'm not trying to say or imply anything by this, i'm just curious and want to understand something different to my own way of thinking)

**Comment by jackhftang** [comment]
A1: The reason why global scope variables work is that as long as you do not assign `nil` to the variable. There is always at least one reference to the `Thread[T]`, so GC is not going to recycle it. Another way as I mentioned is to manually allocate memory, keep `ptr Thread[T]` and deallocate manually after use. 

A2: What you want is to execute the file operations sequentially, it does not necessarily be "blocking". Here blocking means that the thread cannot do any other things. The jester example showed that `doSomething` is always executing task sequentially, see in stdout `start i`, `end i`, `start i+1`, `end i+1`... and during sleepAsync the thread can also do other things like responding to other http requests. Though there is one assumption that only one process is working on those files, but multi-thread solution also require this assumption. Besides, you can combine this technique in threadproxy to have the same effect of blocking you want. 

A3: It is because deepcopy in nim seems to have bugs or at least have issues that I don't understand. The very first version of threadproxy is using generic type T, but I found that it is unstable. So I switch to use JsonNode and in my experience JsonNode is quite stable and it is a well-known format and relative good support with serialization/deserialization in stdlib.
